spring:

  ai:
    vectorstore:
      qdrant:
        initialize-schema: true
        host: ${QDRANT_HOST}
        port: ${QDRANT_PORT}
        collection-name: docs_ollama
  config:
    import:
      - aws-secretsmanager:${WEATHER_API_SECRET_NAME}?prefix=weather.
management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans

weather:
  open-weather:
    api-key: ${weather.apikey}
