spring:
  ai:
    openai:
      api-key: none
      timeout: 5m

      chat:
        base-url: http://10.0.0.44:8080/v1
        model: llama31

      embedding:
        base-url: http://10.0.0.44:8081/v1
        model: nomic-embed

    vectorstore:
      qdrant:
        collection-name: docs_llamacpp