server:
  port: 8075


weather:
  open-weather:
    api-key: "Open Weather Api"

spring:
  application:
    name: mcp-server

  profiles:
    active: remote

  ai:
    mcp:
      server:
        protocol: STREAMABLE
        name: streamable-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "This streamable server provides real-time notifications"

        capabilities:
          tool: true
          resource: false
          prompt: true
          completion: false

        streamable-http:
          mcp-endpoint: /api/mcp
          keep-alive-interval: 30s

    vectorstore:
      qdrant:
        initialize-schema: true
        host: 10.0.0.227
        port: 6334
        collection-name: docs_ollama

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://10.0.0.227:9411/api/v2/spans
