server:
  port: 8075

weather:
  open-weather:
    api-key: "OpenWeather api key"

spring:
  application:
    name: streamable-mcp-server

  profiles:
    active: remote

  datasource:
    url: jdbc:postgresql://localhost:5432/ecomm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true

  ai:
    mcp:
      server:
        protocol: STREAMABLE
        name: streamable-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "This streamable server provides real-time notifications"

        capabilities:
          tool: true
          resource: false
          prompt: true
          completion: false

        streamable-http:
          mcp-endpoint: /api/mcp
          keep-alive-interval: 30s

    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: docs_ollama